apiVersion: v1 
kind: Service 
metadata: 
  name: java-app-service
spec: 
  ports: 
  - nodePort: 30814  
    port: 5000 
    protocol: TCP 
    targetPort: 5000 
  selector: 
    app: java-app
  type: NodePort 
status: 
  loadBalancer: {} 
